[2024-12-08T12:41:03.261+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: json_to_postgres_dag.parse_json_task manual__2024-12-08T12:39:07.542089+00:00 [queued]>
[2024-12-08T12:41:03.272+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: json_to_postgres_dag.parse_json_task manual__2024-12-08T12:39:07.542089+00:00 [queued]>
[2024-12-08T12:41:03.272+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-08T12:41:03.273+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-12-08T12:41:03.273+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-08T12:41:03.289+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): parse_json_task> on 2024-12-08 12:39:07.542089+00:00
[2024-12-08T12:41:03.294+0000] {standard_task_runner.py:55} INFO - Started process 70 to run task
[2024-12-08T12:41:03.296+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'json_to_postgres_dag', 'parse_json_task', 'manual__2024-12-08T12:39:07.542089+00:00', '--job-id', '2442', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp03ddp7pa']
[2024-12-08T12:41:03.297+0000] {standard_task_runner.py:83} INFO - Job 2442: Subtask parse_json_task
[2024-12-08T12:41:03.349+0000] {task_command.py:376} INFO - Running <TaskInstance: json_to_postgres_dag.parse_json_task manual__2024-12-08T12:39:07.542089+00:00 [running]> on host ece2bbff80df
[2024-12-08T12:41:03.411+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=json_to_postgres_dag
AIRFLOW_CTX_TASK_ID=parse_json_task
AIRFLOW_CTX_EXECUTION_DATE=2024-12-08T12:39:07.542089+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-08T12:39:07.542089+00:00
[2024-12-08T12:41:03.413+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 30, in parse_json_to_records
    with open(json_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/complex.json'
[2024-12-08T12:41:03.424+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=json_to_postgres_dag, task_id=parse_json_task, execution_date=20241208T123907, start_date=20241208T124103, end_date=20241208T124103
[2024-12-08T12:41:03.436+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2442 for task parse_json_task ([Errno 2] No such file or directory: '/opt/airflow/dags/data/complex.json'; 70)
[2024-12-08T12:41:03.468+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-08T12:41:03.486+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
