[2024-12-08T12:09:29.533+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dummy_dag.BashIn manual__2024-12-08T12:07:26.781202+00:00 [queued]>
[2024-12-08T12:09:29.548+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dummy_dag.BashIn manual__2024-12-08T12:07:26.781202+00:00 [queued]>
[2024-12-08T12:09:29.549+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-08T12:09:29.550+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2024-12-08T12:09:29.551+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-08T12:09:29.566+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): BashIn> on 2024-12-08 12:07:26.781202+00:00
[2024-12-08T12:09:29.576+0000] {standard_task_runner.py:55} INFO - Started process 8137 to run task
[2024-12-08T12:09:29.579+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dummy_dag', 'BashIn', 'manual__2024-12-08T12:07:26.781202+00:00', '--job-id', '2403', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpb2bg24n3']
[2024-12-08T12:09:29.580+0000] {standard_task_runner.py:83} INFO - Job 2403: Subtask BashIn
[2024-12-08T12:09:29.645+0000] {task_command.py:376} INFO - Running <TaskInstance: dummy_dag.BashIn manual__2024-12-08T12:07:26.781202+00:00 [running]> on host ece2bbff80df
[2024-12-08T12:09:29.710+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dummy_dag
AIRFLOW_CTX_TASK_ID=BashIn
AIRFLOW_CTX_EXECUTION_DATE=2024-12-08T12:07:26.781202+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-08T12:07:26.781202+00:00
[2024-12-08T12:09:29.711+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-08T12:09:29.712+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'instance started']
[2024-12-08T12:09:29.723+0000] {subprocess.py:86} INFO - Output:
[2024-12-08T12:09:29.724+0000] {subprocess.py:93} INFO - /bin/bash: line 1: instance: command not found
[2024-12-08T12:09:29.724+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-12-08T12:09:29.735+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-08T12:09:29.738+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dummy_dag, task_id=BashIn, execution_date=20241208T120726, start_date=20241208T120929, end_date=20241208T120929
[2024-12-08T12:09:29.754+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2403 for task BashIn (Bash command failed. The command returned a non-zero exit code 127.; 8137)
[2024-12-08T12:09:29.792+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-08T12:09:29.822+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
