[2024-12-08T12:07:28.071+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dummy_dag.BashIn manual__2024-12-08T12:07:26.781202+00:00 [queued]>
[2024-12-08T12:07:28.082+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dummy_dag.BashIn manual__2024-12-08T12:07:26.781202+00:00 [queued]>
[2024-12-08T12:07:28.083+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-08T12:07:28.084+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-12-08T12:07:28.084+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-08T12:07:28.099+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): BashIn> on 2024-12-08 12:07:26.781202+00:00
[2024-12-08T12:07:28.104+0000] {standard_task_runner.py:55} INFO - Started process 8035 to run task
[2024-12-08T12:07:28.107+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dummy_dag', 'BashIn', 'manual__2024-12-08T12:07:26.781202+00:00', '--job-id', '2402', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpgfl5pnax']
[2024-12-08T12:07:28.108+0000] {standard_task_runner.py:83} INFO - Job 2402: Subtask BashIn
[2024-12-08T12:07:28.165+0000] {task_command.py:376} INFO - Running <TaskInstance: dummy_dag.BashIn manual__2024-12-08T12:07:26.781202+00:00 [running]> on host ece2bbff80df
[2024-12-08T12:07:28.223+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dummy_dag
AIRFLOW_CTX_TASK_ID=BashIn
AIRFLOW_CTX_EXECUTION_DATE=2024-12-08T12:07:26.781202+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-08T12:07:26.781202+00:00
[2024-12-08T12:07:28.225+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-08T12:07:28.226+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'instance started']
[2024-12-08T12:07:28.235+0000] {subprocess.py:86} INFO - Output:
[2024-12-08T12:07:28.236+0000] {subprocess.py:93} INFO - /bin/bash: line 1: instance: command not found
[2024-12-08T12:07:28.237+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-12-08T12:07:28.246+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-08T12:07:28.250+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dummy_dag, task_id=BashIn, execution_date=20241208T120726, start_date=20241208T120728, end_date=20241208T120728
[2024-12-08T12:07:28.262+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2402 for task BashIn (Bash command failed. The command returned a non-zero exit code 127.; 8035)
[2024-12-08T12:07:28.280+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-08T12:07:28.305+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
