[2024-12-08T08:25:24.058+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dummy_dag.send_email_notification manual__2024-12-08T08:25:22.620955+00:00 [queued]>
[2024-12-08T08:25:24.070+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dummy_dag.send_email_notification manual__2024-12-08T08:25:22.620955+00:00 [queued]>
[2024-12-08T08:25:24.071+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-12-08T08:25:24.075+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-12-08T08:25:24.076+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-12-08T08:25:24.093+0000] {taskinstance.py:1383} INFO - Executing <Task(EmailOperator): send_email_notification> on 2024-12-08 08:25:22.620955+00:00
[2024-12-08T08:25:24.098+0000] {standard_task_runner.py:55} INFO - Started process 629 to run task
[2024-12-08T08:25:24.101+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dummy_dag', 'send_email_notification', 'manual__2024-12-08T08:25:22.620955+00:00', '--job-id', '2351', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp7zd8mf36']
[2024-12-08T08:25:24.102+0000] {standard_task_runner.py:83} INFO - Job 2351: Subtask send_email_notification
[2024-12-08T08:25:24.173+0000] {task_command.py:376} INFO - Running <TaskInstance: dummy_dag.send_email_notification manual__2024-12-08T08:25:22.620955+00:00 [running]> on host ece2bbff80df
[2024-12-08T08:25:24.248+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dummy_dag
AIRFLOW_CTX_TASK_ID=send_email_notification
AIRFLOW_CTX_EXECUTION_DATE=2024-12-08T08:25:22.620955+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-08T08:25:22.620955+00:00
[2024-12-08T08:25:24.259+0000] {base.py:71} INFO - Using connection ID 'smtp_default' for task execution.
[2024-12-08T08:25:24.260+0000] {email.py:229} INFO - Email alerting: attempt 1
[2024-12-08T08:25:24.261+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-12-08T08:25:24.270+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dummy_dag, task_id=send_email_notification, execution_date=20241208T082522, start_date=20241208T082524, end_date=20241208T082524
[2024-12-08T08:25:24.285+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2351 for task send_email_notification ([Errno 111] Connection refused; 629)
[2024-12-08T08:25:24.315+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-12-08T08:25:24.336+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
